#pragma once

#include "AiManagerBase.h"
#include "AiGroupStatsManager.h"
#include "AiInventoryManager.h"
#include "AiManagerBase.h"
#include "AiManagerRegistry.h"
#include "AiManagerRegistryAware.h"
#include "AiMoveManager.h"
#include "AiQuestManager.h"
#include "AiSocialManager.h"
#include "AiSpellManager.h"
#include "AiStatsManager.h"
#include "AiTargetManager.h"
#include "AiStrategyManager.h"
